FROM serengil/deepface:latest

RUN apt-get update && apt-get install -y --no-install-recommends openssl procps python3 python3-pip && apt-get clean && \
    mkdir -p /etc/ssl/private && openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout /etc/ssl/private/key.pem -out /etc/ssl/private/cert.pem -subj "/C=TR/ST=KOCAELI/O=NovaVision AI/CN=novavision.ai"
WORKDIR /opt/project
COPY . /opt/project
RUN pip install --no-cache-dir -r requirements.dev
RUN ["chmod", "+x", "/opt/project/entrypoint.sh"]
ENTRYPOINT ["/bin/bash", "/opt/project/entrypoint.sh"]